output: output/jamba_large.jsonl
batch_size: null
batch_queue: false
open_kwargs_file: null

defaults:
  - _self_
  - dataset: swebenc_verified_tuned_small # swebench_verified_tuned_128k, swebench_verified_tuned_random_small, swebench_verified_tuned
  - model: jamba_large
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .