output: ???
batch_size: null
batch_queue: true
open_kwargs_file: null

defaults:
  - _self_
  - dataset: swebench_verified_tuned
  - model: gpt4o
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .