output: Qwen-swebench-32k
batch_size: null
batch_queue: true
open_kwargs_file: null

defaults:
  - _self_
  - dataset: swebench_tuned_32k
  - model: qwen2.5-1M
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .